# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: latest
          use-public-rspm: true
          
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck remotes reticulate
          cache-version: 3
          upgrade: 'TRUE'
          
      - name: Install Miniconda
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "reticulate::install_miniconda()"
          
      - name: setup bertopicrenv
        run: |
          reticulate::conda_create(envname = bertopicr_env, 
                conda = paste0(reticulate::miniconda_path(), "/condabin/conda"),
                packages = c("bertopic==0.15.0", "numpy==1.24.3", "hdbscan==0.8.29", 
                "umap-learn==0.5.3", "pandas==2.0.2", "scikit-learn==1.2.2", 
                "pytorch==2.0.0","tqdm==4.65.0", "sentence-transformers==2.2.2",
                "plotly==5.15.0", "openai==0.27.8"))
                
          #Get correct Python path
          python_path <- reticulate::conda_list()
          python_path <- python_path[python_path["name"] == bertopicr_env, 2]
        
          writeLines(
            paste0("RETICULATE_PYTHON=", virtualenv_python(python_path)),
            Sys.getenv("GITHUB_ENV"))

         

      - uses: r-lib/actions/check-r-package@v2
